### ISSUE TITLE
Viewsreference patch conflict with localgov_paragraphs 

### ISSUE THREAD

**Issue by graham-web** [localgovdrupal/localgov_subsites#100]
I'm currently seeing the following output from composer since updating everything today:
>  - Applying patches for drupal/viewsreference
>   https://www.drupal.org/files/issues/2022-07-06/viewsreference_schema-2957529-13.patch (Fix schema #2957529)
>  https://www.drupal.org/files/issues/2020-07-16/2957529-10.viewsreference.patch (Implement configuration schema for Views reference field storage+settings and widget+formatter https://www.drupal.org/project/viewsreference/issues/2957529)
>   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2020-07-16/2957529-10.viewsreference.patch

Since https://github.com/localgovdrupal/localgov_paragraphs/commit/ee0032ad0cf64be0030b8fc7cd98e03b1fd82acb was committed, there are now two competing versions of the same patch for viewsreference in my LGD install!

**Comment by ekes** [comment]
Can you do a quick grep to see where the [2020-07-16/2957529-10.viewsreference.patch](https://www.drupal.org/files/issues/2020-07-16/2957529-10.viewsreference.patch) is coming from? I've just done one on my codebase and it's not coming up; and a github search of the repos isn't being very helpful for either.

**Comment by graham-web** [comment]
@ekes Sorry, should have made that clearer! https://github.com/localgovdrupal/localgov_subsites/blob/fea2c2678310396b7ebbdaf65b01ead8516a84d1/composer.json#L23
