### ISSUE TITLE
Rogue BS 'row' class causing problems

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_subsites#38]
I'm working on an issue with text not lining up in Croydon and have narrowed it down to a 'row' class in the following file that's adding negative margins: 

https://github.com/localgovdrupal/localgov_subsites/blob/master/templates/layout--onecol--flexible.html.twig 

rather than fix it within the croydon theme I think it would be best to remove it at the local gov theme level - this class relies on being within a container class called 'container' which isn't declared here so removing it shouldn't be an issue. Looking at the git log this seems to be a BHC inherited thing - it was probably given the container class when in use at Brighton.

**Comment by cjstevens78** [comment]
PR: https://github.com/localgovdrupal/localgov_subsites/pull/39

**Comment by willguv** [comment]
Cheers @cjstevens78, copying @markconroy

**Comment by cjstevens78** [comment]
merged and done thanks
