### ISSUE TITLE
Check what homepage functionality is missing

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_subsites#43]
Croydon and Lambeth both have the ability to create a homepage from a SubSite landing page

We need to confirm this can be done in https://demo.localgovdrupal.org

If not, we need to list any missing functionality or styling and address it in a future sprint

**Comment by willguv** [comment]
@finnlewis @stephen-cox @msayoung we didn't get time to discuss this, and I'm keen that we have a presentable homepage by the end of this sprint

Can we take half an hour to discuss in the next day or two?

Thanks

**Comment by willguv** [comment]
I'm working down the homepage and will add notes when I've finished, see:

https://test.localgovdrupal.org/homepage

Tom kindly provided the documentation Croydon content designers use:

https://docs.google.com/document/d/1LZ2zONzuk4r-uvMUHKIpucOdz7dbKGvX8c_fJ3XOQ4U/edit?usp=sharing

**Comment by willguv** [comment]
@msayoung and @markconroy particularly, but open to all

I've built a homepage the best I can at https://test.localgovdrupal.org/homepage

I've been comparing with the layout of https://www.croydon.gov.uk, and thinking about an MVP demo site homepage

We ought to split this work into three parts (I'll break this into separate cards after we've discussed)

## 1) Make the page look presentable enough for the demo site (next sprint)

### Banner

- the "welcome text" needs styling
- Croydon's search box is hard coded. Let's discuss whether we want a search box and the best way to add this

### Call to action buttons

- need styling

### Services IA

- styling
- it's not clear how to hide some services under "show more services". We don't need this immediately, but should consider how to offer this

### Latest news

- styling
- I added "newsroom teasers" which allow editors to add free text and images. We need to test with News

### Email updates and follow us

- Not convinced this meets the common needs of councils, so suggest parking until we have a working group

### Subsite teasers

- styling

### Setting this page as the homepage

- how is this done?
- who has permission to do it?

### Related work

- agree a plan for the services menu. Have we finalised what's included in LGD?
- how to edit the footer? What content are we adding for the demo site
- write demo content

## 2) Tidy up the UX for content designers (when we return from the break)

### Hide page menu
- Under "banner and colour theme" which feels like the wrong place for it
- "Description" is better - at least it's visible
- check whether we're using "description" elsewhere on LGD. Doesn't feel consistent to me

### Adding a page section
- content designers have to click the "+" at the top or bottom of a section, pick "page section" (it's the only option) and then pick the section. Feels like one too many steps
- why do "two column" and "three column" options add a full width column above and below? Feels odd, and adds more columns to the page than necessary

<img width="661" alt="Screenshot 2021-07-02 at 09 52 31" src="https://user-images.githubusercontent.com/708140/124249477-d5a6a400-db1b-11eb-991e-cf6ce6b5a121.png">

<img width="296" alt="Screenshot 2021-07-02 at 09 57 18" src="https://user-images.githubusercontent.com/708140/124249668-fff86180-db1b-11eb-9cba-30fd8efa8fc3.png">

- "save" button color needs to be consistent. It's grey on the "add page section" column, and blue elsewhere

- are the box control icons (eg pen icon, bin) clear to users and accessible?

### Documentation

- we definitely need documentation for creating a homepage from a subsite overview - it's one of the most complex things LGD does
- the notes Tom provided are a great start https://docs.google.com/document/d/1LZ2zONzuk4r-uvMUHKIpucOdz7dbKGvX8c_fJ3XOQ4U/edit?usp=sharing

## 3) make sure we talk to content designers about this/ consider a working group

We've not had any conversations with content designers about how these pages are built. I think we should do this before the end of the Beta, and tighten up functionality based on their feedback.

This feels like working group territory to me - our existing councils use the homepage in different ways, but it feels like there are common patterns we should explore.

It's not as pressing as Forms, Subsites, Directories so let's play this by ear.

**Comment by markconroy** [comment]
@willguv it would be great to get what you have done exported as demo_content so we can test it with my theme.

**Comment by willguv** [comment]
@markconroy it was a bit rushed to get something to look at. I think let's add making some decent homepage content to the early part of next sprint, then you can test against it

**Comment by markconroy** [comment]
If it's create with subsites, then anything subsites can do should work as is

**Comment by stephen-cox** [comment]
Done - sprint 5
