### ISSUE TITLE
Break out localgov_subsites_paragraphs in to its own repo 

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_subsites#48]
I'd like to use localgov_subsites_paragraphs on a project for microsites, and don't want the rest of localgov_subsites. Could we split out localgov_subsites_paragraphs in to its own repo? 

@stephen-cox @ekes @finnlewis @gosia-mlynarczyk @BFC-Digital-Services  - any thoughts?

**Comment by stephen-cox** [comment]
Should be easy enough. There was a previous discussion on whether localgov_subsites_paragraphs should actually be a submodule of localgov_paragraphs, like [localgov_homepage_paragraphs](https://github.com/localgovdrupal/localgov_paragraphs/tree/2.x/modules/localgov_homepage_paragraphs) already are.

Do you need other LocalGov paragraph types or just the subsite ones?

**Comment by markconroy** [comment]
I hadn't realised we had a localgov_paragraphs module already. 

I'd suggest we move subsites paragraphs to that module. 

I'd also suggest we have all the paragraph types at the same level, and not use sub modules. I can imagine plenty of cases where people might want to use a paragraph type from the home page on other pages, but might not realise it's even there until they have homepage paragraphs enabled. 

I think just a repo of "these are the paragraph types that LGD provides" would be the easiest.

**Comment by ekes** [comment]
The paragraphs have _a_ _lot_ of dependencies, based on the fields and entity references they add. Putting them all in one bucket means you require all the geo modules, all the media modules, all the cropping configuration, all the content types referenced, all the dependencies that they then require in turn. Which is already proving a pain point with media and installing in a profile.

**Comment by andybroomfield** [comment]
[localgov_homepage_paragraphs](https://github.com/localgovdrupal/localgov_paragraphs/tree/2.x/modules/localgov_homepage_paragraphs) was for the legacy homepage (used by BHCC site). I think everyone else uses a subsite for their homepage, and even the new build of BHCC has its own homepage type and special paragraphs, not using this sub-module.
So that should be safe to remove?

**Comment by markconroy** [comment]
I _think_ I have homepage_paragraphs enabled on sites, but would have to check.

Also, if it's in the distro for the past 2 years, there's probably a good chance that others may have enabled it and be using it, not realising how specific the use case for it was.

**Comment by ekes** [comment]
From discussion in stand-up just now, and from bashing my head around dependency hell, my suggestion would be to collect paragraphs into (sub)modules primarily by dependency. 
If it depends on geo entity and geo module, that's one group of paragraphs; if it depends on media image, another that also pulls in the default cropping support modules; etc. 
There could be (a} separate one/s for legacy / deprecated paragraphs (localgov_homepage_paragraphs?).

I'm guessing this might be possible to do now, as long as the moved paragraph type modules are enabled? It's templates and preprocess classes that are required? Or will template names or something need to change thus breaking any themes that are overriding them?

**Comment by msayoung** [comment]
Ooh, we did this. https://github.com/localgovdrupal/localgov_subsites/pull/95 
Thanks all.
