### ISSUE TITLE
Select a version of Layout Paragraphs to use - instead of `dev`

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_subsites#49]
Our composer.json is asking for he dev version of the layout_paragraphs module - https://github.com/localgovdrupal/localgov_subsites/blob/2.x/composer.json#L10

This is dangerous as we have no idea what might be in a dev branch at any moment. 

There is a 1.0 version released back in May. I think we should probably request that, `^1.0.0` instead.

**Comment by finnlewis** [comment]
Good call @markconroy .

I'm also looking at layout_paragrpahs 2.x branch which has some significant improvements to the usability

But we should probably pin the existing branch to the `^1.0.0` as you suggest.
