### ISSUE TITLE
Make the homepage look presentable enough for the demo site

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_subsites#50]
This follows on from my discovery in sprint 5 of what the out of the box homepage experience is like

See https://github.com/localgovdrupal/localgov_subsites/issues/43 and [my test homepage](https://test.localgovdrupal.org/homepage)

I suggested 3 pieces of work, and think we should attempt the first one in sprint 7

### Banner

- the "welcome text" needs styling
- Croydon's search box is hard coded. Let's discuss whether we want a search box and the best way to add this

### Call to action buttons

- need styling

### Services IA

- styling
- it's not clear how to hide some services under "show more services". We don't need this immediately, but should consider how to offer this

### Latest news

- styling
- I added "newsroom teasers" which allow editors to add free text and images. We need to test with News

### Email updates and follow us

- Not convinced this meets the common needs of councils, so suggest parking until we have a working group

### Subsite teasers

- styling

### Setting this page as the homepage

- how is this done?
- who has permission to do it?

### Related work

- agree a plan for the services menu. Have we finalised what's included in LGD?
- how to edit the footer? What content are we adding for the demo site
- write demo content

**Comment by finnlewis** [comment]
Note: the https://test.localgovdrupal.org/homepage might be reinstalled at any time, so this is just being used as a playground.

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_demo/issues/47

**Comment by finnlewis** [comment]
@stephen-cox suggests that we build out better content on the demo site.

https://demo.localgovdrupal.org/

@stephen-cox will work with @markconroy to tag a release of the localgov_base theme and then get this deployed onto the demo site.

@willguv will then produce a home page on the demo site.

@msayoung might also produce some news demo content.

**Comment by stephen-cox** [comment]
@willguv I have deployed the new theme to the demo site (https://demo.localgovdrupal.org/) so it's now ready for you to create the new homepage.

**Comment by finnlewis** [comment]
Just taking this one over, as we've made some advances on demo content this morning and I am now wrapping it up into the localgov_demo module.

**Comment by finnlewis** [comment]
We had another demo content session today, the home page is looking better: 

![image](https://user-images.githubusercontent.com/326588/133641525-cf4fd0ff-1e05-4336-99e8-3f1779e61395.png)

We'll have another one tomorrow then wrap up the content into the localgov_demo module again.

**Comment by stephen-cox** [comment]
Done - sprint 9
