### ISSUE TITLE
Subsites navigation - page you are on should show as text not a link

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_subsites#59]
This is a legacy issue we currently have a ticket for at Croydon but as is it is present within LGD it makes sense for it to be fixed here. When using the subsite navigation, the name of the page you are currently viewing should show as plain text rather than a link to the page.

Using this example page:

http://localgov.dev.mark.ie/bereavement-services/scarfolk-crematorium

See 'Scarfolk Crematorium' is linked.

<img width="1228" alt="Screenshot 2021-09-20 at 17 33 54" src="https://user-images.githubusercontent.com/11304107/134039876-8c84ee2f-fc6c-4b72-bf55-de6c7b50fcc1.png">

**Comment by cjstevens78** [comment]
PR for this here: https://github.com/localgovdrupal/localgov_subsites/pull/69

**Comment by markconroy** [comment]
PR merged. Let's close this.
